
package by.nbrb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-31T15:31:30.590+03:00
 * Generated source version: 2.7.10
 * 
 */
public final class ExRatesSoap_ExRatesSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.nbrb.by/", "ExRates");

    private ExRatesSoap_ExRatesSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ExRates.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ExRates ss = new ExRates(wsdlURL, SERVICE_NAME);
        ExRatesSoap port = ss.getExRatesSoap();  
        
        {
        System.out.println("Invoking metalsRef...");
        by.nbrb.MetalsRefResponse.MetalsRefResult _metalsRef__return = port.metalsRef();
        System.out.println("metalsRef.result=" + _metalsRef__return);


        }
        {
        System.out.println("Invoking lastDailyExRatesDate...");
        javax.xml.datatype.XMLGregorianCalendar _lastDailyExRatesDate__return = port.lastDailyExRatesDate();
        System.out.println("lastDailyExRatesDate.result=" + _lastDailyExRatesDate__return);


        }
        {
        System.out.println("Invoking ingotsLastDate...");
        javax.xml.datatype.XMLGregorianCalendar _ingotsLastDate__return = port.ingotsLastDate();
        System.out.println("ingotsLastDate.result=" + _ingotsLastDate__return);


        }
        {
        System.out.println("Invoking startDate...");
        int _startDate_periodicity = 0;
        javax.xml.datatype.XMLGregorianCalendar _startDate__return = port.startDate(_startDate_periodicity);
        System.out.println("startDate.result=" + _startDate__return);


        }
        {
        System.out.println("Invoking currenciesRefMonthly...");
        by.nbrb.CurrenciesRefMonthlyResponse.CurrenciesRefMonthlyResult _currenciesRefMonthly__return = port.currenciesRefMonthly();
        System.out.println("currenciesRefMonthly.result=" + _currenciesRefMonthly__return);


        }
        {
        System.out.println("Invoking metalsPrices...");
        int _metalsPrices_metalId = 0;
        javax.xml.datatype.XMLGregorianCalendar _metalsPrices_fromDate = null;
        javax.xml.datatype.XMLGregorianCalendar _metalsPrices_toDate = null;
        by.nbrb.MetalsPricesResponse.MetalsPricesResult _metalsPrices__return = port.metalsPrices(_metalsPrices_metalId, _metalsPrices_fromDate, _metalsPrices_toDate);
        System.out.println("metalsPrices.result=" + _metalsPrices__return);


        }
        {
        System.out.println("Invoking lastMonthlyExRatesDate...");
        javax.xml.datatype.XMLGregorianCalendar _lastMonthlyExRatesDate__return = port.lastMonthlyExRatesDate();
        System.out.println("lastMonthlyExRatesDate.result=" + _lastMonthlyExRatesDate__return);


        }
        {
        System.out.println("Invoking stockAddRates...");
        javax.xml.datatype.XMLGregorianCalendar _stockAddRates_onDate = null;
        by.nbrb.StockAddRatesResponse.StockAddRatesResult _stockAddRates__return = port.stockAddRates(_stockAddRates_onDate);
        System.out.println("stockAddRates.result=" + _stockAddRates__return);


        }
        {
        System.out.println("Invoking exRatesDyn...");
        int _exRatesDyn_curId = 0;
        javax.xml.datatype.XMLGregorianCalendar _exRatesDyn_fromDate = null;
        javax.xml.datatype.XMLGregorianCalendar _exRatesDyn_toDate = null;
        by.nbrb.ExRatesDynResponse.ExRatesDynResult _exRatesDyn__return = port.exRatesDyn(_exRatesDyn_curId, _exRatesDyn_fromDate, _exRatesDyn_toDate);
        System.out.println("exRatesDyn.result=" + _exRatesDyn__return);


        }
        {
        System.out.println("Invoking stockAddRatesLastDate...");
        javax.xml.datatype.XMLGregorianCalendar _stockAddRatesLastDate__return = port.stockAddRatesLastDate();
        System.out.println("stockAddRatesLastDate.result=" + _stockAddRatesLastDate__return);


        }
        {
        System.out.println("Invoking refRateOnDate...");
        javax.xml.datatype.XMLGregorianCalendar _refRateOnDate_onDate = null;
        by.nbrb.RefRateOnDateResponse.RefRateOnDateResult _refRateOnDate__return = port.refRateOnDate(_refRateOnDate_onDate);
        System.out.println("refRateOnDate.result=" + _refRateOnDate__return);


        }
        {
        System.out.println("Invoking currenciesRef...");
        int _currenciesRef_periodicity = 0;
        by.nbrb.CurrenciesRefResponse.CurrenciesRefResult _currenciesRef__return = port.currenciesRef(_currenciesRef_periodicity);
        System.out.println("currenciesRef.result=" + _currenciesRef__return);


        }
        {
        System.out.println("Invoking currenciesRefDaily...");
        by.nbrb.CurrenciesRefDailyResponse.CurrenciesRefDailyResult _currenciesRefDaily__return = port.currenciesRefDaily();
        System.out.println("currenciesRefDaily.result=" + _currenciesRefDaily__return);


        }
        {
        System.out.println("Invoking ingotsPrices...");
        javax.xml.datatype.XMLGregorianCalendar _ingotsPrices_onDate = null;
        by.nbrb.IngotsPricesResponse.IngotsPricesResult _ingotsPrices__return = port.ingotsPrices(_ingotsPrices_onDate);
        System.out.println("ingotsPrices.result=" + _ingotsPrices__return);


        }
        {
        System.out.println("Invoking exRatesDaily...");
        javax.xml.datatype.XMLGregorianCalendar _exRatesDaily_onDate = null;
        by.nbrb.ExRatesDailyResponse.ExRatesDailyResult _exRatesDaily__return = port.exRatesDaily(_exRatesDaily_onDate);
        System.out.println("exRatesDaily.result=" + _exRatesDaily__return);


        }
        {
        System.out.println("Invoking metalsLastDate...");
        javax.xml.datatype.XMLGregorianCalendar _metalsLastDate__return = port.metalsLastDate();
        System.out.println("metalsLastDate.result=" + _metalsLastDate__return);


        }
        {
        System.out.println("Invoking refRateDyn...");
        by.nbrb.RefRateDynResponse.RefRateDynResult _refRateDyn__return = port.refRateDyn();
        System.out.println("refRateDyn.result=" + _refRateDyn__return);


        }
        {
        System.out.println("Invoking exRatesMonthly...");
        javax.xml.datatype.XMLGregorianCalendar _exRatesMonthly_onDate = null;
        by.nbrb.ExRatesMonthlyResponse.ExRatesMonthlyResult _exRatesMonthly__return = port.exRatesMonthly(_exRatesMonthly_onDate);
        System.out.println("exRatesMonthly.result=" + _exRatesMonthly__return);


        }

        System.exit(0);
    }

}
